// apps/react-child/src/App.tsx
import { useDispatch, useSelector } from 'react-redux';
import { HashRouter, NavLink, Routes, Route } from 'react-router-dom';
import { Button, message } from 'antd';
import { RootState } from './store';
import { increment } from './store/counterSlice';
import { HomeView } from './views/HomeView';
import { AboutView } from './views/AboutView';

export function App() {
  const dispatch = useDispatch();
  const value = useSelector((s: RootState) => s.counter.value);
  const [messageApi, contextHolder] = message.useMessage();

  return (
    <>
      {contextHolder}
      <HashRouter>
        <div className="page p-4">
        <div className="card head">
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}>
            <div style={{ fontWeight: 700 }}>React 子应用（Redux + React Router）</div>
            <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
              <i className="iconfont icon-placeholder" aria-hidden="true" style={{ fontSize: 18 }} />
              <NavLink to="/" className="link">
                首页
              </NavLink>
              <NavLink to="/about" className="link">
                关于
              </NavLink>
            </div>
          </div>
        </div>

        <div className="card" style={{ marginTop: 12 }}>
          <h3 style={{ marginTop: 0 }}>Redux 示例</h3>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ fontSize: 18 }}>count: {value}</div>
            <Button
              type="primary"
              onClick={() => {
                dispatch(increment());
                messageApi.open({
                  type: 'success',
                  content: 'react-child: 调用了 antd message'
                });
              }}
            >
              +1
            </Button>
          </div>
        </div>

        <div className="content">
          <Routes>
            <Route path="/" element={<HomeView />} />
            <Route path="/about" element={<AboutView />} />
          </Routes>
        </div>
      </div>
      </HashRouter>
    </>
  );
}

// apps/vue-child/src/App.vue
<template>
  <div class="page p-4">
    <div class="card head">
      <div style="display: flex; align-items: center; justify-content: space-between; gap: 12">
        <div style="font-weight: 700">Vue 子应用（Pinia + Vue Router）</div>
        <div style="display: flex; align-items: center; gap: 10">
          <i class="iconfont icon-placeholder" aria-hidden="true" style="fontSize: 18px" />
          <router-link to="/" class="link">首页</router-link>
          <router-link to="/about" class="link">关于</router-link>
        </div>
      </div>
    </div>

    <div class="card" style="margin-top: 12px">
      <h3 style="margin-top: 0">Pinia 示例</h3>
      <div style="display: flex; align-items: center; gap: 12">
        <div style="fontSize: 18px">count: {{ counter.count }}</div>
        <el-button type="primary" @click="addWithMessage">+1</el-button>
      </div>
    </div>

    <div class="content">
      <router-view />
    </div>
  </div>
</template>

<script setup lang="ts">
import { inject } from 'vue';
import { ElMessage } from 'element-plus';
import { useCounterStore } from './stores/counter';

const counter = useCounterStore();

const mountContainer = inject<HTMLElement>('mfeMountContainer');

const addWithMessage = () => {
  counter.increment();
  ElMessage({
    type: 'success',
    message: 'vue-child: 调用了 Element Plus ElMessage',
    appendTo: mountContainer ?? document.body
  });
};
</script>
